spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factory
    username: postgres
    password: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
